//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Clientes.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Clientes {
	public Object idCliente;
	public Object nombre;
	public Object apellido;
	public Object telefono;
	public Object ciudadOrigen;
	public Object eMail;
	public void solicitarHabitacion() {
	
	}
	
	public void solicitarCancelacion() {
	
	}
	
	public void solicitarDesplazamiento() {
	
	}
	
	public void pagarReservacion() {
	
	}
	
	public void cancelarReservacion() {
	
	}
}
