//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Habitaciones.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Habitaciones {
	public Object idHabitacion;
	public Object ocupacion;
	public Object estado;
	public Object tipo;
	public Object precio;
	public void ingresarOcupantes() {
	
	}
	
	private void solicitarLimpieza() {
	
	}
}
