//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Operarios.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Operarios {
	public Object idOperario;
	public Object nombre;
	public Object apellido;
	private Object contrasena;
	public Object turno;
	public void realizarReservacion() {
	
	}
	
	public void consultarReservaciones() {
	
	}
}
