//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Registro.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Registro {
	public Object idRegistro;
	public Object idOpeario;
	public Object idReservacion;
	public Object fechaModificacion;
}
