//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reservaciones.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Reservaciones {
	public Object idResercacion;
	public Object idHabitacion;
	public Object idCliente;
	public Object fechaEntrada;
	public Object fechaSalida;
	public Object idTarifa;
	public Object estado;
	public Object origenReservacion;
}
