//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tarifas.java
//  @ Date : 28/10/2021
//  @ Author : 
//
//




public class Tarifas {
	public Object idTarifa;
	public Object descuento;
	public void aplica() {
	
	}
}
